### ISSUE TITLE
Camera movement

### ISSUE THREAD

**Issue by DhruvaSambrani** [DhruvaSambrani/pentra#3]

**Comment by DhruvaSambrani** [comment]
@20akshay00 what is this?

**Comment by 20akshay00** [comment]
The viewport that player sees. Right now, character can walk right off the screen; the camera should move with the player (or a bit cooler but extra, follow/tween with a slight delay).

**Comment by DhruvaSambrani** [comment]
Awaiting #6

**Comment by DhruvaSambrani** [comment]
Fixed with #21
