### ISSUE TITLE
Lighting system

### ISSUE THREAD

**Issue by DhruvaSambrani** [DhruvaSambrani/pentra#5]

**Comment by DhruvaSambrani** [comment]
Awaiting #6

**Comment by 20akshay00** [comment]
How can we go about this? If we aim for a 'realistic' light system with rays respecting walls and edges, etc, we need the information of collision boxes of the map elements. But, #6 tackles collisions with an image processing approach and doesn't have that information either.. So we either need to generate a separate map property to hold collision info, or think about a less realistic lighting system.

**Comment by DhruvaSambrani** [comment]
Yes I was thinking about it. We can go a similar way to what we were trying to do before
We first create a "grid" around the player, of size 16 pixels or so
Then we 1/x the transparency every radial distance, and reduce further depending on average color
